### ISSUE TITLE
Modify MLKitObjectAnalyzer.kt

### ISSUE THREAD

**Issue by Jai-GAY** [googlesamples/arcore-ml-sample#5]
[src/main/java/com/google/ar/core/examples/java/ml/mlkit/](https://github.com/googlesamples/arcore-ml-sample#configure-ml-kits-classification-model) no such file

credentials.json also not found

**Comment by devbridie** [comment]
888be9e3e1bd05dfd829e2eae7850d80eff3dfad

credentials.json being missing is correct; these should be supplied by the developer. Please see information on how to [create a service account here](https://cloud.google.com/vision/docs/setup).
